Add state with saving functionality, rewrite some objects in order to make it work
RayBarneveldInc/Dartin pull request #32
Opened 2021-09-29 12:48 UTC by tr4wzified

2021-09-29 13:00 UTC, rodeknopje requested changes

2021-09-29 13:00 UTC, rodeknopje commented on Dartin/Dartin.Application/Models/Turn.cs
> +            Throw1 = throws[1];
denk dat dit throw2, en throw3 moeten worden.

2021-09-29 13:09 UTC, rodeknopje commented on Dartin/Dartin.Application/Models/Turn.cs
> +        public Throw Throw2
Ik denk dat het beter is om deze throws in een array te doen

2021-09-29 13:40 UTC, Hoekstraa requested changes

2021-09-29 13:40 UTC, Hoekstraa commented on Dartin/Dartin.Application/Models/Turn.cs
> +        [JsonConstructor]
Graag je classes in een consistente volgorde opbouwen.
e.g.
variabelen
constructor
functies
properties

2021-09-29 13:40 UTC, Hoekstraa commented on Dartin/Dartin.Application/Models/Leg.cs
> +        [JsonProperty("turns")]
Kunnen we deze functies niet templaten?
Ze zijn allemaal praktisch hetzelfde.

2021-09-29 13:54 UTC, tr4wzified commented
Review gehad:
Dubbele methoden naar abstracte klasse.
Niet gerelateerde logica in aparte PR.

2021-09-29 14:49 UTC, tr4wzified commented
Singleton

2021-10-01 10:07 UTC, Hoekstraa reviewed
Ziet er beter uit, even een overlegje over hebben met z'n allen?

2021-10-01 12:12 UTC, rodeknopje approved these changes

2021-10-01 12:13 UTC, Hoekstraa approved these changes
Prima, zorgt voor 'extra werk' in de models. We moeten rekening houden met dat dit in elke model is geimplementeerd..

2021-10-01 12:16 UTC, ork44 approved these changes

2021-10-01 12:20 UTC, merged