Add Throws kunnen nu geparsed worden.
RayBarneveldInc/Dartin pull request #50
Opened 2021-10-04 15:59 UTC by ork44

Throws kunnen nu geparsed worden.

close #43

2021-10-04 17:33 UTC, Hoekstraa requested changes
Je returnt meteen de gecalculeerde waarde, met multiplier.
Maar deze willen we voor latere berekeningen beschikbaar houden.
Mij lijkt het returnen van een lijst met 3 throws beter.

2021-10-04 19:22 UTC, tr4wzified commented
> 
> 
> Je returnt meteen de gecalculeerde waarde, met multiplier. Maar deze willen we voor latere berekeningen beschikbaar houden. Mij lijkt het returnen van een lijst met 3 throws beter.

Eens, maar je voert 1 throw in dus je krijgt dan natuurlijk geen lijstje terug maar een enkel Throw object. Lijkt me trouwens ook logisch dat je 50 of 25 in moet kunnen vullen ipv `obull` en `bull`.

2021-10-04 19:27 UTC, Hoekstraa commented
Excuus, raak nog in de war met dat ambigu Throw.
1 Throw dan, met 3 worpen, ehhh schoten.
En ben het eens met dat er een aantal aliasen moeten kunnen zijn voor de bulls.
ibull, 50/25, inner, outer, wat dan ook maar.

2021-10-04 20:18 UTC, Hoekstraa requested changes
Bij voorkeur heb ik liever geen externe dependencies bij unit tests,
maar sure.
Toss > Throw.
Graag wil ik nog wel de mogelijkheid om wat anders dan bull/obull in te kunnen vullen.

Maar qua logica is het verder prima.

2021-10-04 20:22 UTC, rodeknopje approved these changes

2021-10-04 21:21 UTC, tr4wzified requested changes

2021-10-04 21:21 UTC, tr4wzified commented on Dartin/Dartin.Application/Managers/Parser.cs
> +        public static Toss ParseThrow(string _throw)
Maak van de rest van de gebruiken van het woord 'Throw' in functies & parameters ook even Toss, en zie idd nog wel graag de 25 / 50 detectie als alias van bull.

2021-10-05 08:19 UTC, tr4wzified approved these changes
nicee

2021-10-05 08:22 UTC, Hoekstraa approved these changes
Top

2021-10-05 08:26 UTC, merged