[Feature] Overzicht van wedstrijden #15
RayBarneveldInc/Dartin pull request #56
Opened 2021-10-08 11:46 UTC by MauricePonte

Added matchesView/Model 

Added View en ViewModel for Matches
Added unit test for filtering

Refactor on MatchDefinition

Fixed main menu to work for now
Fixed unittest involving MatchDefinitions

2021-10-08 11:48 UTC, ork44 approved these changes

2021-10-08 11:56 UTC, rodeknopje requested changes

2021-10-08 11:56 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/MatchesViewModel.cs
> +            ScreenManager.GetInstance().SwitchViewModel(new MatchDefinitionViewModel(new MatchDefinition()));
moet dit niet `ScreenManager.GetInstance().SwitchViewModel(new MatchDefinitionViewModel(null));` zijn je checkt namelijk later of de original match null is maar nu is de original match nooit null, correct me if I'm wrong tho.

2021-10-11 08:19 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/MatchesViewModel.cs
> +            ScreenManager.GetInstance().SwitchViewModel(new MatchDefinitionViewModel(new MatchDefinition()));
Ik heb die null check eruit gehaald, dit vindt ik mooier/duidelijker  :)

2021-10-12 18:59 UTC, Jacsquare approved these changes
prima, zie foto volgens mij is return niet nodig
![afbeelding](https://user-images.githubusercontent.com/43779942/137013510-54b295fd-408a-4aab-96bb-1fe279a0e951.png)

2021-10-12 22:53 UTC, tr4wzified requested changes

2021-10-12 22:53 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/MainMenuViewModel.cs
> +            throw new NotImplementedException();
Als je de ViewName met => doet zou ik deze methodes ook met => doen (probeer ik ook aan te houden bij simpele one liners). Dit is niet de reden waarom ik block tho, zie tweede comment

2021-10-12 22:53 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/MatchesViewModel.cs
> +        }
Ik zou deze Clear() en foreach herschrijven, kan gewoon in 1 line met linq, en sowieso de case insensitive comparator gebruiken.

Matches = State.Instance.Matches.Where(match => match.Name.Contains(filter, StringComparison.OrdinalIgnoreCase);

Die OrdinalIgnoreCase werkt alleen in .NET Core 2.1+ btw Maurice, voordat je m bij CS probeert

Waarom initialiseert de FilterPlayers de lijst als die nog niet bestaat? Is dat het werk van een filter/search?

2021-10-13 11:12 UTC, rodeknopje approved these changes

2021-10-15 17:57 UTC, rodeknopje requested changes

2021-10-15 17:57 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/MatchDefinitionViewModel.cs
> -            ScreenManager.GetInstance().SwitchViewModel(new ScoreboardViewModel(CurrentObject));
Zou dit terug kunnen, nu kunnen we geen match meer starten

2021-10-15 18:13 UTC, rodeknopje requested changes

2021-10-15 18:13 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> -            LastName = string.Empty;
Zou je deze terug kunnen zetten, hierdoor is de modal nu prefilled met de first and lastname die je de vorige keer hebt ingevuld, dit valt overigs ook buiten de scope

2021-10-15 18:15 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> -            LastName = string.Empty;
Jaa veel buiten de scope, dit was toegevoegd omdat Player een constructor had. Maar deze is niet nodig. De prefill kan dan worden toegevoegd in de XML

2021-10-15 18:15 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/MatchDefinitionViewModel.cs
> -            ScreenManager.GetInstance().SwitchViewModel(new ScoreboardViewModel(CurrentObject));
Met nieuwe commit aangepast

2021-10-15 18:20 UTC, rodeknopje requested changes

2021-10-15 18:20 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> +                State.Instance.Players.Add(new Player());
Als je nu een speler aanmaakt dan heeft hij dus geen naam terwijl je wel een naam invult in de modal, blijkbaar was de constructor wel nodig 😄, maar gebruik hier anders  `new Player { FirstName = FirstName, LastName = LastName}` als je perse zonder constructor wilt doen

2021-10-15 18:23 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> +                State.Instance.Players.Add(new Player());
Jaa je past direct die dingen aan in die View en je Back button zou de player (die dan word aangemaakt) uit de state moeten verwijderen, dus niet nodig dacht ik :) Anders krijg je spelers met FirstName LastName, toch?

2021-10-15 18:27 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> -            LastName = string.Empty;
Dit gaat om de Add() die heeft geen prefill nodig maar op het moment dat deze modal tevoorschijn komt moeten de first and lastname allebij empty zijn, dat wordt nu met twoway binding gedaan in de xaml

2021-10-15 18:31 UTC, rodeknopje approved these changes

2021-10-15 18:31 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/MatchDefinitionViewModel.cs
> +            OriginalMatch.LegsToWinSet = CurrentObject.SetsToWin;
Denk dat dit niet helemaal klopt :D

2021-10-15 18:36 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> +                State.Instance.Players.Add(new Player());
ik snap niet helemaal wat je bedoelt, ik wil als ik een speler aanmaak toch gwn de firstname en lastname kunnen invoeren

2021-10-15 18:40 UTC, rodeknopje requested changes
test

2021-10-15 18:51 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/MatchDefinitionViewModel.cs
> +            OriginalMatch.LegsToWinSet = CurrentObject.SetsToWin;
Jaa want in de constructor maak ik een nieuw object (CurrentObject) die vul ik via de viewModel. (Zodat ik niet de State aanpas) en daarna moet ik dat weer terugzetten naar het originele object, zodat de state wel aangepast word.

2021-10-15 18:53 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> +                State.Instance.Players.Add(new Player());
Dat kan ook ? Je past de First en Last in die pop up aan van dit object, via de properties, Daar heb je dan geen constructor voor nodig

2021-10-15 18:54 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/MatchDefinitionViewModel.cs
> +            OriginalMatch.LegsToWinSet = CurrentObject.SetsToWin;
ik bedoel de laatste regel :)

2021-10-15 18:54 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> -            LastName = string.Empty;
Jaa doordat de Player geen Constructor meer heeft zijn die gwn leeg dus klopt het weer

2021-10-15 18:55 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/MatchDefinitionViewModel.cs
> +            OriginalMatch.LegsToWinSet = CurrentObject.SetsToWin;
oeps :)

2021-10-15 19:10 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> -            LastName = string.Empty;
Deze FistName en LastName zijn bindings naar de xaml textboxjes, dit heeft niet zoveel met de player constructor te maken. Maak nu maar is een player aan dan zie je dat hij geen naam krijgt. Deze waardes moeten dus wel aan de nieuwe player worden geassigned. Of je dat nu met een constructor doet of op een andere manier maakt niet uit. 

als je deze twee regels weer terughaald en dan die `new Player { FirstName = FirstName, LastName = LastName}` doet in de feedback hieronder doet hij het gwn weer.

2021-10-16 11:38 UTC, ork44 requested changes
Blijf binnen je scope

2021-10-16 11:48 UTC, ork44 requested changes

2021-10-16 11:48 UTC, ork44 commented on Dartin/Dartin.UnitTests/PlayersViewModelTests.cs
> -            var player1 = new Player("yob", "ama");
Waarom is dit veranderd?

2021-10-16 11:51 UTC, ork44 requested changes

2021-10-16 11:51 UTC, ork44 commented on Dartin/Dartin.UnitTests/ScoreboardViewModelTest.cs
> -            SubmitTossInputs(vm, "t20", "t20", "t20");
Waarom zijn de tests gecomment?

2021-10-16 15:42 UTC, rodeknopje commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> +                State.Instance.Players.Add(new Player());
Klopt indd, zou je dat ook willen doen dat de First en LastName wel worden gezet, want als je nu dus een speler maakt krijgt deze geen naam

2021-10-18 07:31 UTC, MauricePonte commented on Dartin/Dartin.UnitTests/ScoreboardViewModelTest.cs
> -            SubmitTossInputs(vm, "t20", "t20", "t20");
Zijn kapot helaas, moet met de maker er even naar kijken. Staat op mn lijstje

2021-10-18 07:32 UTC, MauricePonte commented on Dartin/Dartin.UnitTests/PlayersViewModelTests.cs
> -            var player1 = new Player("yob", "ama");
Teruggezet

2021-10-18 07:32 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> +                State.Instance.Players.Add(new Player());
Teruggezet naar oude situatie

2021-10-18 07:32 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/PlayersViewModel.cs
> -            LastName = string.Empty;
teruggezet naar oude situatie

2021-10-18 08:03 UTC, rodeknopje approved these changes

2021-10-18 08:21 UTC, tr4wzified approved these changes

2021-10-18 08:22 UTC, ork44 approved these changes
bg

2021-10-18 08:23 UTC, merged