Matches en MatchDefinition refactor + bugfixes
RayBarneveldInc/Dartin pull request #80
Opened 2021-10-20 08:37 UTC by MauricePonte

2021-10-20 10:37 UTC, tr4wzified requested changes
Ziet er goed uit, mooi gebruik van nullability operator met ??= en de bool visibility converter, alleen variabele naam kan misschien iets duidelijker?

2021-10-20 10:37 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +        public bool PlayerTurnIndicator
Kun je deze ff renamen zodat het duidelijk is welke player er aan de beurt is? Iets van Player1IsNext? Dan weet je in 1 oogopslag wie er aan de beurt is wanneer deze true/false is

2021-10-20 10:37 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +        public bool PlayerLegStartIndicator
zie comment hierboven

2021-10-20 11:12 UTC, boele approved these changes

2021-10-21 13:59 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +        public bool PlayerTurnIndicator
tsja, beetje stijlkeuze lijkt me. Ik vind het niet zo zeer verhelderend als ik 2 bools zou hebben.

2021-10-22 10:49 UTC, Hoekstraa commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +        public bool PlayerTurnIndicator
Maak het een int i.p.v. een bool en je bent klaar.

2021-10-22 10:50 UTC, Hoekstraa commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +        public bool PlayerTurnIndicator
Als je helemaal fancy wilt zijn maak je een enum.

2021-10-22 12:24 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +        public bool PlayerTurnIndicator
Ik bedoel niet dat je twee bools moet maken, alleen een rename zodat je weet wat de bool aangeeft

2021-10-22 12:49 UTC, tr4wzified approved these changes

2021-10-25 08:15 UTC, Hoekstraa requested changes
Graag nog de playerTurnIndicator wijzigen in een int.
Anders is PlayerTurnIndicator 1 gelijk aan speler 2, wat verwarring kan opleveren.

2021-10-25 08:41 UTC, Hoekstraa approved these changes
Geapproved, onder verantwoordelijkheid van Maurice.

2021-10-25 09:18 UTC, merged