Add match average per player to ScoreboardView, change UI slightly, fix turn indicator being on the wrong player
RayBarneveldInc/Dartin pull request #81
Opened 2021-10-20 10:15 UTC by tr4wzified

2021-10-20 12:37 UTC, tr4wzified commented
Er wordt in de branch ook gekeken naar legs & sets indicatoren, die zijn bugged atm

2021-10-22 14:07 UTC, tr4wzified commented
Ready for merging

2021-10-25 08:36 UTC, rodeknopje approved these changes

2021-10-25 08:45 UTC, MauricePonte requested changes
Die toggle is er uitgehaald, zie comment voor fix

2021-10-25 08:45 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +                TogglePlayerTurnIndicator();
PlayerTurnIndicator = !PlayerTurnIndicator;

2021-10-25 08:45 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +                ToggleLegStartedIndicator();
PlayerLegStartIndicator = !PlayerLegStartIndicator;

2021-10-25 08:47 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/ScoreboardViewModel.cs
> +                ToggleLegStartedIndicator();
Prima, mergen we eerst dan die van jou? Dan merge ik de main hierin

2021-10-25 13:17 UTC, Hoekstraa approved these changes
Prima, met 2 vragen.

2021-10-25 13:17 UTC, Hoekstraa commented on Dartin/Dartin.Application/Extensions/Extensions.cs
> +            if (list != null && list.Any())
Verwacht je dat list ooit null is?

2021-10-25 13:17 UTC, Hoekstraa commented on Dartin/Dartin.Application/Models/MatchDefinition.cs
> +            return -1;
Waarom moet deze functie -1 teruggeven?
als dat niet nodig is kan je alle checks weghalen (want dan is het resultaat 0, wat in mijn ogen een correct resultaat is).

2021-10-25 13:23 UTC, MauricePonte approved these changes
code ok

2021-10-25 13:24 UTC, tr4wzified commented on Dartin/Dartin.Application/Extensions/Extensions.cs
> +            if (list != null && list.Any())
Ja, dat kwamen we tegen bij het gebruik in linq

2021-10-25 13:26 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/MatchDefinition.cs
> +            return -1;
Average geeft een exception als de speler niet aanwezig is of er geen sets zijn. -1 leek ons duidelijk om aan te geven dat er iets misging, maar het zou niet de gehele applicatie moeten laten crashen.

2021-10-25 13:36 UTC, merged