Match statistic per player new model
RayBarneveldInc/Dartin pull request #82
Opened 2021-10-22 09:44 UTC by Jacsquare

2021-10-22 11:01 UTC, MauricePonte requested changes
ff je build fixen en vragen naar mijn comments als je daar niet mee eens bent

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/Converters/IndexPlusOneConverter.cs
> +    public class IndexPlusOneConverter : IValueConverter
MarkupExtension aan toevoegen? Dan kan je hem makkelijker in je Xaml gebruiken, voor voorbeeld zie BoolToVisibilityConverter.cs en voor die use in xaml zie MatchesView.xaml regel 29

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/Converters/WonOrLostConverter.cs
> +    public class WonOrLostConverter : IMultiValueConverter
Zie comment hierboven :)

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +                if (s.WinnerId == match.Players[0].Id) setsWon++;
match.Players[0].Id > moet dit dan ook niet voor match.Players[1].Id ?

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +        public int avgScore { get; set; }
public properties met HoofdLetter aub

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +        public void TotalWins(MatchDefinition match)
Als deze functie alleen maar properties set, zou ik hem SetTotalWins noemen, zelfde geld voor MatchAverages

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +            int TotalScore = 0;
deze dan weer niet met hoofdletter

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/MatchReportViewModel.cs
> +        public string PlayerOne => PlayerString(0);
hier gaat iets mis.  Ik neem aan dat je deze als binding wilt gebruiken? Dan kan  je in je xaml met playerOne.Name hetzelfde  bereiken. Die dan ook met hoofdletter moet

2021-10-22 11:01 UTC, MauricePonte commented on Dartin/Dartin.Application/ViewModels/MatchReportViewModel.cs
> +        public MatchDefinition MatchInfo1 => SetsPerPlayer(0);
Ik zou dan de player als parameter meegeven ipv de index

2021-10-22 11:10 UTC, Hoekstraa requested changes

2021-10-22 11:10 UTC, Hoekstraa commented on Dartin/Dartin.Application/Converters/IndexPlusOneConverter.cs
> +            int newIndex = 1;
Ik zou deze converter zo generiek mogelijk maken.
Waarom een extra var? `1 + (int)value' kan ook.
En waarom cast je het naar int? Verwacht je geen float, long, double? 
Daarnaast kan de naam in principe ook gewoon PlusOneConverter zijn.

2021-10-22 11:10 UTC, Hoekstraa commented on Dartin/Dartin.Application/Converters/WonOrLostConverter.cs
> +                if (playerID == (Guid)values[3]) text += " - Started";
Waar het kan een && gebruiken i.p.v. een if in een if a.u.b.

2021-10-22 11:10 UTC, Hoekstraa commented on Dartin/Dartin.Application/Converters/WonOrLostConverter.cs
> +            if ((int)values[1] == 1) playerID = (Guid)App.Current.Properties["playeroneID"]; else playerID = (Guid)App.Current.Properties["playertwoID"];
Waarom converten naar int? e.g. zelfde als vorige comment.

2021-10-22 11:10 UTC, Hoekstraa commented on Dartin/Dartin.Application/Models/Leg.cs
> +        public Player Winner { get; set; } = null;
Waarom is dit een Player i.p.v. een Guid van een Player?

2021-10-22 11:10 UTC, Hoekstraa commented on Dartin/Dartin.Application/Converters/WonOrLostConverter.cs
> +        }
Kan je voor deze converter als value niet meteen de GUID meegeven i.p.v. de Player? Zou de code makkelijker en leesbaarder maken.

2021-10-22 11:10 UTC, Hoekstraa commented on Dartin/Dartin.Application/Models/Set.cs
> +        private Player _winner = null;
Waarom is dit een Player object in plaats van een Guid van de Player?

2021-10-22 12:47 UTC, tr4wzified requested changes

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Converters/WonOrLostConverter.cs
> +            if ((int)values[1] == 1) playerID = (Guid)App.Current.Properties["playeroneID"]; else playerID = (Guid)App.Current.Properties["playertwoID"];
Doe if else op een nieuwe line, lastig te lezen zo en niet C# convention (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#layout-conventions)

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/Leg.cs
> +        public Player Winner { get; set; } = null;
Dit bestaat al, haal deze weg en merge de main

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +        public int avgScore { get; set; }
eens

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +            int TotalScore = 0;
Properties van een class dus met hoofdletter als ze public zijn (bij private lowercase + underscore ervoor), variabelen in een scope van een methode zonder hoofdletter

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/Set.cs
> +        private Player _winner = null;
Winner weghalen, merge de main want dit is er allemaal al

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/Turn.cs
> +            if (player == null) PlayerId = Guid.Empty; else PlayerId = player.Id;
if else niet op single line

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/MatchReportViewModel.cs
> +        public string PlayerString(int id)
Doe gewoon Player[id].Name in de xaml? Waarom is hier een aparte methode voor

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +                    foreach (Turn t in l.Turns)
Variabele namen even uitschrijven

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/Models/MatchStatsPlayer.cs
> +                            FirstNineDartsTotal += turnTotal;
Ik snap niet precies wat hier gebeurt, kunnen jullie uitleggen wat FirstNineDartsTotal precies is? Je houdt de 9 darters toch al bij in die single line if hierbeneden (line 66)?

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/MatchReportViewModel.cs
> +            MatchDefinition deepcopy = JsonConvert.DeserializeObject<MatchDefinition>(copyser);
??????? Waarom wordt hier je Match property geserialized, meteen weer gedeserialized en gereturned?

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.Application/ViewModels/MatchReportViewModel.cs
> +                foreach (Leg l in s.Legs)
Single letter variabelen herschrijven

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.UnitTests/MatchReportStatsTest.cs
> +        public void legsWon()
Hoofdletter bij public methoden, zet ook 'Test' vooraan dus TestLegsWon(), dat beschrijft veel beter wat er gebeurt en dat doen we overal

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.UnitTests/MatchReportStatsTest.cs
> +            BindingList<Player> spelers = new BindingList<Player>();
spelers => players

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.UnitTests/MatchReportStatsTest.cs
> +            gooien1.Add(t1);
Geen Nederlandse variable namen

2021-10-22 12:47 UTC, tr4wzified commented on Dartin/Dartin.UnitTests/MatchReportStatsTest.cs
> +            //MatchConfiguration configlol = new MatchConfiguration(2, 2, 501);
Comments weghalen

2021-10-25 11:06 UTC, Hoekstraa approved these changes
Ik vind 'm nu wel bole.

2021-10-25 11:08 UTC, MauricePonte approved these changes
code ok

2021-10-27 08:36 UTC, tr4wzified approved these changes
Ik vertrouw erop dat het wel goed komt, mergen wordt nog wel ff dingetje

2021-10-27 09:07 UTC, merged