[Feature] Nationaliteit van speler
RayBarneveldInc/Dartin pull request #91
Opened 2021-10-27 14:09 UTC by MauricePonte

added player nationality with icons
refactored some xaml

fixed #88

2021-10-27 14:54 UTC, tr4wzified requested changes
Ziet er goed uit qua code maar het scoreboard is nu kapot geloof ik? Zodra ik iets invoer krijg ik een exception, plus de VS tekst ontbreekt nu

2021-10-27 18:33 UTC, MauricePonte commented
> 
> 
> Ziet er goed uit qua code maar het scoreboard is nu kapot geloof ik? Zodra ik iets invoer krijg ik een exception, plus de VS tekst ontbreekt nu @tr4wzified 

Word gefikst in nieuwe scoreboard UI zie PR #92

2021-10-28 12:53 UTC, ork44 approved these changes
prima

2021-10-28 12:54 UTC, rodeknopje approved these changes

2021-10-28 12:55 UTC, Jacsquare reviewed
Deze is vrij hetzelfde als de scoreboard ui change volgens mij? Of zie ik dat verkeerd?

Edit: ah dit is de functionaliteit en in de scoreboard ui changes wordt het gefixed in scoreboard, I see

2021-10-28 12:57 UTC, Hoekstraa approved these changes
Niet gecompileerd/uitgevoerd.
Qua structuur en opzet prima!

2021-10-29 07:59 UTC, merged